[package]
name = "cionc"
version = "0.1.0"
authors = ["Robbepop <robbepop@web.de>"]

[[bin]]
name = "cionc"

[dependencies.cionc_parser]
path = "src/parser"

[[test]]
name = "test_cionc_parser"
path = "src/parser/lib.rs"
