[package]
name = "cionc"
version = "0.1.0"
authors = ["Robbepop <robbepop@web.de>"]

[[bin]]
name = "cionc"

[dependencies.cionc_parser]
path = "src/parser"

[dependencies]
clap = "2.2"
string-interner = "0.2.1"

[[test]]
name = "test_cionc_parser"
path = "src/parser/lib.rs"
